spring:
  application:
    name: playgound
  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true
  datasource:
    url:  jdbc:postgresql://localhost:5436/playgroundposgresql
    username: playgroundposgresql
    password: playgroundposgresql
  jpa:
    hibernate:
      ddl-auto: none
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration
    repair: true



server:
  port: 8082
